export const USERS_GET_ALL = "USERS_GET_ALL";
export const USERS_GET_ALL_SUCCESS = "USERS_GET_ALL_SUCCESS";
export const USERS_GET_ALL_ERROR = "USERS_GET_ALL_ERROR";

export const USERS_GET_ONE = "USERS_GET_ONE";
export const USERS_GET_ONE_SUCCESS = "USERS_GET_ONE_SUCCESS";
export const USERS_GET_ONE_ERROR = "USERS_GET_ONE_ERROR";

export const USERS_UPDATE_ONE = "USERS_UPDATE_ONE";
export const USERS_UPDATE_ONE_SUCCESS = "USERS_UPDATE_ONE_SUCCESS";
export const USERS_UPDATE_ONE_ERROR = "USERS_UPDATE_ONE_ERROR";

export const USERS_DELETE_ONE = "USERS_DELETE_ONE";
export const USERS_DELETE_ONE_SUCCESS = "USERS_DELETE_ONE_SUCCESS";
export const USERS_DELETE_ONE_ERROR = "USERS_DELETE_ONE_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const LOGOUT = "LOGOUT"